channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.7.0
  - cloudpickle==2.2.1
  - matplotlib==3.7.3
  - numpy==1.25.2
  - packaging==23.1
  - psutil==5.9.5
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - scipy==1.11.2
name: mlflow-env
